### ISSUE TITLE
Wireframe - Contact page

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v11-toucans-team-15#10]
How the general call-to-action page will look like.

Consideratons:
Google Maps with standing out marker
Directions option (very key)
Though since we are nowadays digital and not as reliant in visiting places. This can also be striped down to just visual aspects of the office, official contact options (email/phone) & a form.
Usually when a form & email option are presented. People always just take the email and ignore the form.

**Comment by awalaja** [comment]
The map was a great idea. Direction can be inserted too.
You will ask where the form is? I included a button on every page top and bottom "Tell us about your project". When it is clicked upon, a page pops up that collects visitors details like, names, email, phone number and what kind of service the visitor requires.
<img width="299" alt="contact" src="https://user-images.githubusercontent.com/17528088/64666685-08674000-d44f-11e9-9454-3bf0586fb716.png">

**Comment by mainangethe** [comment]
@awalaja
We need to showcase that form on a separate page.
We need to showcase that FAQ as an accordion as well.
This page doesn't have the page header or page footer.

**Comment by awalaja** [comment]
1. The idea is for form to pop-up, when the "Contact us" button is clicked. Ermm, i need to add that.
2. Accordion is a great idea. I am pumped.
3. It does not have a footer like the others because footer is about how to contact the agency, we are on the page that tells you that. So i added FAQs. 
Thoughts?

**Comment by mainangethe** [comment]
Noted about the footer. Make sense. 

Page header though would still help in page identification.
