### ISSUE TITLE
Branding - Template Naming

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v11-toucans-team-15#11]
We need a fictitious organization that we will position as the Digital Agency.

**Comment by mainangethe** [comment]
@awalaja  - I've come up with two (2) names which I think we can use.
1. Atlas: Sounds like a cool name for a digital agency
2. Colma: Just joined our two (2) names.  

I'll let you decide which one of the above suits you so that I can continue with the branding strategy.

**Comment by awalaja** [comment]
Atlas sounds generic. Let's go with Colma.
