### ISSUE TITLE
Style Guide - Font selection

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v11-toucans-team-15#12]
Headings & Body

**Comment by mainangethe** [comment]
@awalaja  - For this task I opted in reviewing only Google Fonts for ease of importing it to our template.

There are four(4) combinations that I have gone with:

_Legend: Heading / Body Text_

1. PT Sans / PT Sans Narrow
2. Fjalla One / Noto Sans
3. Playfair Display / Sours Sans Pro
4. Alegreya / Lato

[Preview the Font Choices](https://docs.google.com/document/d/1Ztz--lZVWTgUFn6WoAp_jmdz-OjypdhnqFF1WVSttzQ/edit?usp=sharing)

**Comment by awalaja** [comment]
Wow, great font selection. Website already alive.
My first choice will be between Fjalla One / Noto Sans and Alegreya / Lato.

**Comment by mainangethe** [comment]
Because the logo will be from a serif font. Let's go with **Alegreya / Lato**.
