### ISSUE TITLE
Design - Homepage

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v11-toucans-team-15#19]
Based on agreed homepage wireframe.
Using PS.
960 Grid System.

**Comment by awalaja** [comment]
the prototype created deviated a bit from the wireframe we agreed upon.

**Comment by awalaja** [comment]
The tabs for projects isn't necessary. This is a homepage, we can include this on the portfolio page since it is a coll feature.

**Comment by mainangethe** [comment]
Footer changes: 
- Because we are LTR society. Ranking changed the social media icons and the contact details.
- Also the form will be dynamic. Just wanted the design to be there instead of just a linkable heading/button.

![homepage-v1](https://user-images.githubusercontent.com/41260290/65231679-94750980-dad8-11e9-814b-66ada1adc905.jpg)
