### ISSUE TITLE
Design - Works/Portfolio page

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v11-toucans-team-15#22]

**Comment by awalaja** [comment]
![Web 1920 – 1](https://user-images.githubusercontent.com/17528088/65468466-15772c80-de5c-11e9-826b-3ae083ead69e.png)

**Comment by awalaja** [comment]
And when a project is clicked:

![Web 1920 – 2](https://user-images.githubusercontent.com/17528088/65468588-7b63b400-de5c-11e9-9a85-f4603e957214.png)

brief, Approach and accolades are clickable buttons
