### ISSUE TITLE
Wireframe - Homepage

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v11-toucans-team-15#5]
How the homepage will look like.
As high level as it can be to aid in actual page design

Can look for inspiration from multiple platforms: Awwwards, Dribbble, Behance etc.

**Comment by awalaja** [comment]
Homepage features:
1. Ditched the home button on the home page. It is assumed the first pag you get to on any webste is its HOME.
2. Background image suggestion - rich vibrant image, can be a showcase photo.
3. the slideshow at the bottom should showcase pictures of previous jobs handled by the agency.
<img width="188" alt="index" src="https://user-images.githubusercontent.com/17528088/64665918-49aa2080-d44c-11e9-8837-1391691f3755.png">

**Comment by mainangethe** [comment]
@awalaja
Seen and confirmed.
