### ISSUE TITLE
Wireframe - About

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v11-toucans-team-15#6]
How the about the agency page will look like.
As high level as it can be to aid in actual page design

Can look for inspiration from multiple platforms: Awwwards, Dribbble, Behance etc.

**Consideration:** 
History, Balanced text to image ratio.

**Comment by awalaja** [comment]
Nothing much to say on the page. The features we will have to discuss, but this is what i cam up with:
<img width="152" alt="about" src="https://user-images.githubusercontent.com/17528088/64666068-e076dd00-d44c-11e9-9b4e-0cc2d4ec21b6.png">

**Comment by mainangethe** [comment]
@awalaja - What does the four boxes represent?

**Comment by awalaja** [comment]
Images of people and the office space.
Mood: happy and ambient
