### ISSUE TITLE
Wireframe - Products/Services

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v11-toucans-team-15#7]
How the "What we Offer/Do" page will look like.
As high level as it can be to aid in actual page design

Can look for inspiration from multiple platforms: Awwwards, Dribbble, Behance etc.

**Considerations:**
Benefits & Value propositions need to stand out

**Comment by awalaja** [comment]
Each service can be styled by making it pop up a bit when hovered over, with a brief description of what that service is about.
<img width="155" alt="services" src="https://user-images.githubusercontent.com/17528088/64666507-6e9f9300-d44e-11e9-8c35-ebf50df43792.png">

**Comment by mainangethe** [comment]
@awalaja 

What does the boxes with the service name represent? An image or background-color.

And where will someone go if they want to know more about a particular service offering?

**Comment by awalaja** [comment]
The boxes are titled with the service the agency is offering. it is going to have an image.
Iwas thinking of a pop-up that then show cases details of what the agnency is offering when each box is clicked.

**Comment by mainangethe** [comment]
I personally think for such a page; information is more important than pictorials. 
Furthermore; it is harder to represent digital services with images. I think icons would be a better option.

For the popup. Include a secondary page showing how it should appear.
