### ISSUE TITLE
Wireframe - Teams

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v11-toucans-team-15#8]
How the "Our People/Our Culture" page will look like.
As high level as it can be to aid in actual page design

Can look for inspiration from multiple platforms: Awwwards, Dribbble, Behance etc.

**Considerations:**
Talk about culture, benefits; and very visual.
Mood: Happy, Collaborative - Agency, Creative

**Comment by awalaja** [comment]
We agreed to merge this page with the About page., so it is done.
