### ISSUE TITLE
Wireframe - Portfolio

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v11-toucans-team-15#9]
How the "previous works/showcase" page will look like.
As high level as it can be to aid in actual page design

Can look for inspiration from multiple platforms: Awwwards, Dribbble, Behance etc.

**Considerations:**
Filter based on the different products/services they offer.
Very visual.
Case Studies have a higher conversion rate

**Comment by awalaja** [comment]
The portfolio is page s just a fullscreen of previous jobs showcased.
As for styling, i was thinking when hovered over, an overlay appears on each photo telling the user the title of the job and possible may have a link pointing to details about the job - maybe a website or another page on our website.
<img width="150" alt="projects" src="https://user-images.githubusercontent.com/17528088/64666232-71e64f00-d44d-11e9-8fa7-e574622e2f2d.png">

**Comment by mainangethe** [comment]
@awalaja 

No page header seen.
No filter seen.

I'd rather we limit the view to at max. 4 - 6. To give more room for content.

Also create the showcase page as well. On click. That will be the case study page.

**Comment by awalaja** [comment]
I did not add a page header ecause, the user clicked on "Work" to get to this page. So, i just thought to showcase an album of what the Agency has done in the past. Ofcourse this can be amended.
I don't understand, the filter part.
Showcase? You mean a page that will showcase details for every job done?

**Comment by mainangethe** [comment]
Think about it. If we only relied on links from the header. There would never have page headers on any website. The header section helps identify the page. And allow us to add other complementary features like breadcrumbs. It's a UX issue.

Filter. You can review [this image](https://visualmodo.com/wp-content/uploads/2017/05/portfolio-filter-icon-in-WordPress-1.jpg) to see what I mean.

For the showcase page. Yes I mean a page that will list all about the project clicked.
